#服务端口
server:
  port: 8090
  #注册中心的名字
spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: localhost
  server:
    #配置关闭自我保护，并按需配置Eureka Server清理无效节点的时间间隔（5000ms）
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  client:
    #由于该应用为注册中心，所以设置为false 代表不向注册中心注册自己
    register-with-eureka: false
    #由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以为false
    fetch-registry: false
    #注册中心的地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

