#服务端口
server:
  port: 8091
#服务名称
spring:
  application:
    name: server-provider
  #设置数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/gmall
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
#注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
  instance:
    prefer-ip-address: true
#扫描MyBatis的xml文件
mybatis:
  mapper-locations: classpath:mapper/*.xml
# 控制台打印SQL
logging:
  level:
    com.example.server.provider.mapper: debug